# frozen_string_literal: true

# Generated by TurboCrud.
# This controller is intentionally boring. Boring code is stable code. 😄
class NotesController < ApplicationController
  include TurboCrud::Controller

  def index
    @notes = Note.order(created_at: :desc)
  end

  def new
    @note = Note.new
    render(**turbo_crud_template_for(:new))
  end

  def edit
    @note = Note.find(params[:id])
    render(**turbo_crud_template_for(:edit))
  end

  def create
    @note = Note.new(safe_note_attrs)
    turbo_create(@note, list: Note, success_message: "Note created!")
  end

  def update
    @note = Note.find(params[:id])
    @note.assign_attributes(safe_note_attrs)
    turbo_update(@note, success_message: "Note updated!")
  end

  def destroy
    @note = Note.find(params[:id])
    turbo_destroy(@note, list: Note, success_message: "Note deleted.")
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end

  # Drop stale/unknown keys so generated controllers are resilient when a
  # legacy form still submits attributes that no longer exist on the model.
  def safe_note_attrs
    raw = note_params.to_h
    allowed = raw.slice(*Note.attribute_names)
    unknown = raw.keys - allowed.keys

    if unknown.any?
      raise ArgumentError,
            "Unknown attributes for Note: #{unknown.join(', ')}. " \
            "Run the migration for these columns, then retry."
    end

    allowed
  end
end
