# frozen_string_literal: true

# Generated by TurboCrud.
# This controller is intentionally boring. Boring code is stable code. 😄
class PostsController < ApplicationController
  include TurboCrud::Controller

  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
    render(**turbo_crud_template_for(:new))
  end

  def edit
    @post = Post.find(params[:id])
    render(**turbo_crud_template_for(:edit))
  end

  def create
    @post = Post.new(safe_post_attrs)
    turbo_create(@post, list: Post, success_message: "Post created!")
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(safe_post_attrs)
    turbo_update(@post, success_message: "Post updated!")
  end

  def destroy
    @post = Post.find(params[:id])
    turbo_destroy(@post, list: Post, success_message: "Post deleted.")
  end

  private

  def post_params
    params.require(:post).permit(:title)
  end

  # Drop stale/unknown keys so generated controllers are resilient when a
  # legacy form still submits attributes that no longer exist on the model.
  def safe_post_attrs
    raw = post_params.to_h
    allowed = raw.slice(*Post.attribute_names)
    unknown = raw.keys - allowed.keys

    if unknown.any?
      raise ArgumentError,
            "Unknown attributes for Post: #{unknown.join(', ')}. " \
            "Run the migration for these columns, then retry."
    end

    allowed
  end
end
