# frozen_string_literal: true

# Generated by TurboCrud.
# This controller is intentionally boring. Boring code is stable code. 😄
class PostsController < ApplicationController
  include TurboCrud::Controller

  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    turbo_create(@post, list: Post, success_message: "Post created!")
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    turbo_update(@post, success_message: "Post updated!")
  end

  def destroy
    @post = Post.find(params[:id])
    turbo_destroy(@post, list: Post, success_message: "Post deleted.")
  end

  private

  def post_params
    params.require(:post).permit(:title)
  end
end
