# frozen_string_literal: true

# Generated by TurboCrud.
# This controller is intentionally boring. Boring code is stable code. 😄
class BlogsController < ApplicationController
  include TurboCrud::Controller

  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    turbo_create(@blog, list: Blog, success_message: "Blog created!")
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.assign_attributes(blog_params)
    turbo_update(@blog, success_message: "Blog updated!")
  end

  def destroy
    @blog = Blog.find(params[:id])
    turbo_destroy(@blog, list: Blog, success_message: "Blog deleted.")
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body, :published)
  end
end
