# frozen_string_literal: true

# Generated by TurboCrud.
# This controller is intentionally boring. Boring code is stable code. 😄
class CommentsController < ApplicationController
  include TurboCrud::Controller

  def index
    @comments = Comment.order(created_at: :desc)
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    turbo_create(@comment, list: Comment, success_message: "Comment created!")
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.assign_attributes(comment_params)
    turbo_update(@comment, success_message: "Comment updated!")
  end

  def destroy
    @comment = Comment.find(params[:id])
    turbo_destroy(@comment, list: Comment, success_message: "Comment deleted.")
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body, :published)
  end
end
